ros-visualization/rqt_reconfigure

- src/rqt_reconfigure/dynreconf_client_widget.py
When attempting to update the configuration of a node via dynamic_reconfigure two exceptions could be raised and weren't catched.
`dynamic_reconfigure.DynamicReconfigureParameterException: don't know parameter: ....`
and
`rospy.service.ServiceException: service [/node .../set_parameters] unavailable`
The later one is gets raised because dynamic_reconfigure is not catching it itself and reraising its own exception. I will also issue a PR for the reraising at the dynamic_reconfigure project.
Besides the catches for the occurring exceptions I also already added the catch for the exception I expected will be raised once the PR might have been merged in dynamic_reconfigure.
> Added error handling for dynamic_reconfigure exceptions

- resource/node_selector.ui
> Fixed the bug that truncated text in the qtreeview widget in node_selector.ui

- src/rqt_reconfigure/node_selector_widget.py
- src/rqt_reconfigure/treenode_qstditem.py
This fixes #19.
In current implementation, the `rqt_reconfigure` node tries to connect all nodes available when it starts.
If I understand ROS ecosystem correctly, each connection uses one socket, so if there are many nodes running in one ROS master such as PR2 robot, it can use up all available sockets.
In this pull request, I fixed codes not to connect to all nodes on the start of the node and only connect when any node is selected instead.
I'm not sure if there is any side effect on this change, but at least it works on my laptop, so any feedback from community is very welcome!
> lazy creating of dynamic_reconfigure client for each node

- .gitignore
- CMakeLists.txt
- package.xml
- plugin.xml
- resource/text_filter_widget.ui
- src/rqt_reconfigure/text_filter.py
- test/test_text_filter.py
- test/test_treenode_qstditem.py
This change excludes the actual sources from running linters, but gets the infrastructure in place to do so. I'll follow up with a change to bring the sources into conformance.
Again, the motivation is to help align the ROS 1 package with the ROS 2 package to minimize the drift.
> Fix some linter errors and get tests running

- src/rqt_reconfigure/param_updater.py
In python3, comparing None with other types is no longer possible. This leads to a TypeError in https://github.com/ros-visualization/rqt_reconfigure/blob/master/src/rqt_reconfigure/param_updater.py#L70. The python2 behavior can be reproduced by changing the line as suggested in this PR.
> Avoid TypeError due to NoneType comparison

- CONTRIBUTING.md
- LICENSE
These files are good to have anyway, but we'll need them to pass the `ament_copyright` tests in ROS 2.
> Add LICENSE and CONTRIBUTING.md

- CONTRIBUTING.md
- LICENSE
- src/rqt_reconfigure/filter_children_model.py
- src/rqt_reconfigure/logging.py
- src/rqt_reconfigure/node_selector_widget.py
- src/rqt_reconfigure/param_client_widget.py
- src/rqt_reconfigure/param_editors.py
- src/rqt_reconfigure/param_groups.py
- src/rqt_reconfigure/param_plugin.py
- src/rqt_reconfigure/param_updater.py
- src/rqt_reconfigure/param_widget.py
- src/rqt_reconfigure/paramedit_widget.py
- src/rqt_reconfigure/text_filter.py
- src/rqt_reconfigure/text_filter_widget.py
- src/rqt_reconfigure/treenode_item_model.py
- src/rqt_reconfigure/treenode_qstditem.py
- src/rqt_reconfigure/treenode_status.py
- test/test_text_filter.py
- test/test_treenode_qstditem.py
This change adds a line to the license headers specifying the name of the license that follows. It also re-formats the recently added `LICENSE` and `CONTRIBUTING.md` files to match the templates.
> Re-format license headers to conform to ROS templates

- package.xml
References:
* `python3-yaml`: https://github.com/ros-visualization/rqt_reconfigure/blob/116ee13143ea6dc0a9785cd9a70d5600c64191b8/src/rqt_reconfigure/param_client_widget.py#L44
* `rclpy`: https://github.com/ros-visualization/rqt_reconfigure/blob/116ee13143ea6dc0a9785cd9a70d5600c64191b8/src/rqt_reconfigure/logging.py#L35
* `rqt_console`: https://github.com/ros-visualization/rqt_reconfigure/blob/116ee13143ea6dc0a9785cd9a70d5600c64191b8/src/rqt_reconfigure/text_filter.py#L39
I found no references to `rqt_py_console` - I believe it was added by mistake. @gonzodepedro to confirm.
> Fix ROS 2 package dependencies

- src/rqt_reconfigure/filter_children_model.py
- src/rqt_reconfigure/logging.py
- src/rqt_reconfigure/node_selector_widget.py
- src/rqt_reconfigure/param_client_widget.py
- src/rqt_reconfigure/param_editors.py
- src/rqt_reconfigure/param_groups.py
- src/rqt_reconfigure/param_plugin.py
- src/rqt_reconfigure/param_updater.py
- src/rqt_reconfigure/param_widget.py
- src/rqt_reconfigure/paramedit_widget.py
- src/rqt_reconfigure/text_filter.py
- src/rqt_reconfigure/text_filter_widget.py
- src/rqt_reconfigure/treenode_item_model.py
- src/rqt_reconfigure/treenode_qstditem.py
- src/rqt_reconfigure/treenode_status.py
- test/test_text_filter.py
- test/test_treenode_qstditem.py
This change removes a superfluous license specification in license headers and makes the formatting in the test files' headers the same as the source files'.
I promise this is the last of the license fixups :P
> Another round of license formatting alignment

- package.xml
`catkin_pkg` was previously used in the `setup.py`, but I believe we forgot to remove the dependency when that file got refactored as part of the change to `ament_python`.
@gonzodepedro to confirm.
> Drop explicit catkin_pkg dependency

- src/rqt_reconfigure/node_selector_widget.py
- src/rqt_reconfigure/param_client_widget.py
- src/rqt_reconfigure/param_editors.py
- src/rqt_reconfigure/param_groups.py
- src/rqt_reconfigure/param_plugin.py
- src/rqt_reconfigure/param_updater.py
- src/rqt_reconfigure/param_widget.py
- src/rqt_reconfigure/paramedit_widget.py
- src/rqt_reconfigure/treenode_item_model.py
- src/rqt_reconfigure/treenode_qstditem.py
The goal of this PR is to take some of the more desirable superficial changes that were made in the ROS 2 package and bring that goodness back to the ROS 1 branch.
This also aligns the two branches more closely.
Mostly:
* reorder imports where appropriate
* rename some variables to be more generic
* use explicit syntax when importing from `rqt_reconfigure` itself
> Superficial changes to align ROS 1 and ROS 2 branches

- src/rqt_reconfigure/param_client_widget.py
- src/rqt_reconfigure/param_groups.py
- src/rqt_reconfigure/param_widget.py
- src/rqt_reconfigure/paramedit_widget.py
This will improve logging function compatibility between ROS 1 and ROS 2.
Right now, some log statements cause an exception in ROS 2 due to the differing signatures. This unification will resolve that.
> Use a consistent formatting method when logging

- src/rqt_reconfigure/node_selector_widget.py
The `.message` attribute was present when these were ROS 1 exception types, but they were changed to the standard `Exception` type.
> Fix exception message logging

- src/rqt_reconfigure/param_groups.py
Tabs and other groups seem to be in a (random?) order at the moment. 
This pull request orders them alphabetically.
> Add sorting for tabs

- CMakeLists.txt
- package.xml
- setup.py
Following the guidelines to migrate packages to [noetic](http://wiki.ros.org/noetic/Migration)
- import setup from setuptools instead of distutils-core
- Bump CMake version to avoid CMP0048 warning
This bumps the minimum CMake version to 3.0.2, which is the [minimum supported by ROS Kinetic](https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021) and new enough to default to the NEW behavior of [CMP0048](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html). This avoids a CMake warning when building and testing this package in Debian Buster and Ubuntu Focal.
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Update package build to support ROS Noetic

- src/rqt_reconfigure/param_groups.py
Parameter names are unique even across groups, so we can propagate the flattened list of updated parameters without any problems. The updates coming from dynamic_reconfigure have been structured into a tree, so we need to continue to support both cases.
Closes #25
> Fix loopback propagation for sub-groups of 'apply' groups

- resource/editor_enum.ui
- src/rqt_reconfigure/param_editors.py
- src/rqt_reconfigure/param_groups.py
It can be really easy to accidentally change these values while scrolling along in the editor. This change makes it necessary to focus (clicking on, tabbing to, etc) a widget before the scroll wheel can change it.
Closes #28
> Don't process scroll events unless specifically focused

- src/rqt_reconfigure/param_editors.py
It seems that `dynamic_reconfigure` can handle non-ASCII characters just fine, but the rospy loggers don't take unicode characters very well when running in python 2. This change re-encodes to the native encoding and replaces troublesome characters with '?' in the log messages.
On Python 3, the unicode characters are printed to the log just fine.
Closes #67
> Handle non-ASCII characters in log messages in Python 2

- src/rqt_reconfigure/node_selector_widget.py
This was sort-of working, but the tree of node names on the left side got messed up when you tried to deselect a node. It was completely ineffective for nodes in namespaces.
Turns out we were getting lucky that it worked at all, because the code relied on storing a Qt index object that wasn't supposed to be persistent. So when the tree got more complex, it completely fell apart.
I updated the code to just iterate over all of the items in the tree to find the node we want. We'll only have to do this once, and only if the user is specifying what nodes to open from the command line.
> Fix node selection from command line

- src/rqt_reconfigure/param_groups.py
Keep the 'apply' group's apply button disabled until there are actually some parameter changes pending to be applied. Once they are applied, disable the button again.
This gives the 'apply' group's operation some much needed visual feedback.
> Only enable apply group button when effective

- src/rqt_reconfigure/node_selector_widget.py
- src/rqt_reconfigure/param_widget.py
- src/rqt_reconfigure/paramedit_widget.py
- src/rqt_reconfigure/text_filter_widget.py
New settings being saved:
- Current node list filter
- Currently expanded items in the node list
- Currently active editors (order preserved)
To reconcile the existing behavior for opening nodes from the command line with the restoration of previously open nodes, I opted to treat the nodes on the command line as an explicit list rather than an additive one. So the command line list effectively 'overrides' the previous state.
Requires #77
> Save instance state in rqt settings

- setup.py
- src/rqt_reconfigure/__main__.py
This small change makes it possible to start `rqt_reconfigure` with `python3 -m rqt_reconfigure`.
> Support PEP 338 invocation of rqt_reconfigure

- src/rqt_reconfigure/param_client_widget.py
This change was made in `master` as part of #74. Unlike in ROS 1, the config structure doesn't need a custom YAML constructor to be loaded with the default YAML safe loader.
> Use safe YAML loader

- src/rqt_reconfigure/node_selector_widget.py
This fixes rqt_reconfigure crashing with an index error as reported in bug #92 .
In certain cases, the list of nodes names include an empty string as the name of a node (mostly when a node has crashed or segfaulted)  -- looking it up resulted in the index error reported in bug #92  and rqt reconfigure crashing. The solution is just to skip that "node".
> Address rqt_reconfigure crashing with IndexError  

- src/rqt_reconfigure/node_selector_widget.py
- src/rqt_reconfigure/param_api.py
- src/rqt_reconfigure/param_client_widget.py
- src/rqt_reconfigure/param_editors.py
Don't assume that all ROS nodes support the parameter services. Instead explicitly look for the ListParameters service.
Also, don't assume that all nodes are spinning. Instead of using synchronous service calls (which don't allow for a timeout and will hang if the node is not spinning to process its messages) using an async call, which returns a future that can be used with rclpy.spin_until_future_complete, which supports a timeout.
Note: Parameters can be dynamically added to a node. So, nodes that support the parameter services but currently don't have any parameters could have parameters in the future (currently, all nodes support at least use_sim_time) . So, the presence of the ListParameters service is used as evidence that a node has/can have parameters (since this is used to …
> Use timeouts in service calls to avoid hangs

- src/rqt_reconfigure/param_api.py
The warning looks like:
CNL100 Class definition does not have a new line.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
> Fix a flake8 warning.

- src/rqt_reconfigure/treenode_qstditem.py
`Thread.isAlive()` is deprecated and was removed in Python 3.9. `Thread.is_alive()` should be used instead. This change is backwards compatible (the `is_alive` spelling was added in Python 2.6).
See also https://github.com/ros/ros_comm/pull/2092.
> Replace deprecated isAlive with is_alive

- src/rqt_reconfigure/param_editors.py
This only shows the description when selecting a value, so when the combobox is opened. When it is closed, it shows the overal enum description. Changing that would require too many changes.
Fixes #112
@rickvanosch Feel free to make the changes and open a PR yourself the next time. This one wasn't too difficult. Greetings from the TUe 😉
> Show enum item description as tooltip
